spring:
  application:
    name: Authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/SWP391V2
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
